### ISSUE TITLE
Người dùng

### ISSUE THREAD

**Issue by kienbeo3122** [HoangTran0410/SmartPhone_Store_Manage_Java#6]
A ơi cho e hỏi chút, phần bán hàng của phần mềm này không chọn khuyến mãi được để thanh toán, không biết a có fix lại cái này không ạ, mong phản hồi từ a 
![image](https://user-images.githubusercontent.com/75838759/160321386-0b34d786-a98c-4c5b-8a1c-1d43a774cdf7.png)

**Comment by HoangTran0410** [comment]
@kienbeo3122 Này là do lỗi UI thôi bạn, có 1 input chọn khuyến mãi nữa, mà giao diện width hơi hẹp nên nó bị tụt xuống dòng, nên bị ẩn đi mất

Bạn có thể sửa lại giao diện cho width dài ra chút để khung chọn khuyến mãi không bị tụt xuống nữa.

Khi đó sẽ chọn được khuyến mãi, và có thể thanh toán.
